apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgadmin4.fullname" . }}-configmap
  labels:
    {{- include "pgadmin4.labels" . | nindent 4 }}
data:
  PGADMIN_DEFAULT_EMAIL: {{ .Values.variables.pgadminDefaultEmail }}
  PGADMIN_DEFAULT_PASSWORD: {{ .Values.variables.pgadminDefaultPassword }}