app:
  port: 8080 # port
  image: repository/image
  tag: tag

secret:
  enabled: false
  name: secret-name

ingress:
  enabled: false
  hostname: universalchart.com # change it

pvc:
  enabled: false
  storageClass: default
  accessModes: ReadWriteOnce
  size: 1Gi
  mountPath: /opt/application-home
  subPath: false
  subPathName: application.properties
