{{- $fullName := include "nginx-hello.fullname" . -}}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "nginx-hello.fullname" . }}-nginx-ingress
  labels:
    app: "nginx"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: "{{ .Values.nginx_url }}"
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: {{ template "nginx-hello.fullname" . }}-nginx-service
              servicePort: 8080