apiVersion: v1
kind: Service
metadata:
  name: {{ template "nginx-hello.fullname" . }}-nginx-service
  labels:
    app: "nginx"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: "http-nginx"
    port: 8080
  selector:
    app: "nginx"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}