apiVersion: v1
kind: Service
metadata:
  name: {{ template "universal.fullname" . }}-universal-service
  labels:
    app: "universal"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: "universal"
    port: {{ .Values.app.port }}
  selector:
    app: "universal"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}